amazonexport/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from products.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views

admin.autodiscover()
urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^templates/', include('templates_app.urls')),
    url(r'^generate/$', generate, name="generate"),
    url(r'^upload/$', upload, name="upload"),
    url(r'^mass-upload/$', mass_upload, name="mass_upload"),
    url(r'^designs/$', designs, name="designs"),
    url(r'^designs/edit/(?P<design_id>[\w-]+)/$', edit_design, name="edit_design"),
    url(r'^designs/update/(?P<design_id>[\w-]+)/$', update_design, name="update_design"),
    url(r'^admin/', admin.site.urls),
    url(r'^generated-files/$', generated_files, name="generated_files"),
    url(r'^accounts/login/$', views.LoginView.as_view(), name="login"),
    url(r'^failed-designs/(?P<generation_id>[\w-]+)/$', failed_designs, name="failed_designs"),
    url(r'^assign_accounts/$', assign_accounts, name="assign_account"),
    # url(r'^import_accounts/$', import_accounts, name="import_acccounts"),
    url(r'^import_account_designs/$', import_account_designs, name="import_account_designs"),
    url(r'^delete_sku_codes/$', delete_sku_codes, name="delete_sku_codes"),
    url(r'^delete_account_designs/$', delete_account_designs, name="delete_account_designs"),
    url(r'^delete_batch/(?P<batch_id>[\w-]+)/$', delete_batch, name='delete_batch'),
    url(r'^mass-download/$', mass_download, name='mass_download'),

    url(
        regex=r'^logout/$',
        view=views.logout,
        kwargs={'next_page': '/'},
        name='logout'
    ),

]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

products/models.py
from __future__ import unicode_literals

# from amazoneexport.products.models import ColorVariation
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver

import os
from PIL import Image

# from templates_app.models import ProductTemplate
from django.conf import settings as project_settings
from . import utils
from .search_tags import get_search_tags


# Create your models here.

class Size(models.Model):
    long_name = models.CharField(max_length=255, blank=True)
    short_name = models.CharField(max_length=255, blank=True)
    order_nr = models.IntegerField(default=0)

    def __str__(self):
        return self.long_name


class ProductType(models.Model):
    name = models.CharField(blank=False, max_length=255)
    with_parent = models.BooleanField(default=False)

    def __str__(self):
        return "%s" % (self.name)


class Country(models.Model):
    country_code = models.CharField(blank=False, max_length=255)

    def __str__(self):
        return "%s" % (self.country_code)


class Product_New(models.Model):
    TEMPLATE_CHOICES = (
        ('0', 'Clothing'),
        # ('1', 'Bag'),
        # ('2', 'Pillow'),
        ('3', 'Mugs'),
        # ('4', 'Hats'),
        # ('5', 'Stickers'),
        ('6', 'Home'),
        ('7', 'Luggage'),
    )

    #team = models.ForeignKey('accounts.Team', on_delete=models.CASCADE, default = 0)
    template = models.CharField(default="0", choices=TEMPLATE_CHOICES, max_length=1)
    # template_new = models.ForeignKey(ProductType, on_delete=models.CASCADE, default=1)
    team = models.ForeignKey('accounts.Team', on_delete=models.CASCADE, default=1)
    country = models.ForeignKey('Country', on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    meta_description = models.CharField(max_length=255, blank=True)
    type_full = models.CharField(max_length=255, blank=True) 
    type_short = models.CharField(max_length=255, blank=True)
    browse_node = models.CharField(max_length=255, blank=True)
    departments_name = models.CharField(max_length=255, blank=True)
    static_search_tags = models.CharField(max_length=200, blank=True)
    bullet_point_1 = models.CharField(max_length=1000, blank=True)
    bullet_point_2 = models.CharField(max_length=1000, blank=True)
    bullet_point_3 = models.CharField(max_length=1000, blank=True)
    bullet_point_4 = models.CharField(max_length=1000, blank=True)
    bullet_point_5 = models.CharField(max_length=1000, blank=True)
    material_composition = models.CharField(max_length=255, blank=True)
    item_weight = models.IntegerField(blank=True, null=True)
    parent_only = models.BooleanField(default=False, help_text="For hats, where only parent row is needed")
    sizes = models.ManyToManyField(Size)
    style_name = models.CharField(max_length=255, blank=True)
    size_name = models.CharField(max_length=255, blank=True)
    # liquid_volume = models.CharField(max_length=255, blank=True)
    # liquid_volume_unit_of_measure = models.CharField(max_length=255, blank=True)
    item_length = models.CharField(max_length=255, blank=True)
    item_length_unit_of_measure = models.CharField(max_length=255, blank=True)
    item_width = models.CharField(max_length=255, blank=True)
    item_width_unit_of_measure = models.CharField(max_length=255, blank=True)
    item_height = models.CharField(max_length=255, blank=True)
    item_height_unit_of_measure = models.CharField(max_length=255, blank=True)
    capacity = models.CharField(max_length=255, blank=True)
    capacity_unit_of_measure = models.CharField(max_length=255, blank=True)
    extra_photo = models.ImageField(upload_to='media', blank=True)
    extra_photo_2 = models.ImageField(upload_to='media', blank=True)
    extra_photo_3 = models.ImageField(upload_to='media', blank=True)
    extra_photo_4 = models.ImageField(upload_to='media', blank=True)
    extra_photo_5 = models.ImageField(upload_to='media', blank=True)

    def color_variations(self):
        color_vars = ColorVariation.objects.filter(product=self.id)
        return color_vars

    def __str__(self):  # __str__ for Python 3, __unicode__ for Python 2
        return self.title + ' (' + self.meta_description + ') ' + self.country.country_code


class Product(models.Model):
    TEMPLATE_CHOICES = (
        ('0', 'Clothing'),
        # ('1', 'Bag'),
        # ('2', 'Pillow'),
        ('3', 'Mugs'),
        # ('4', 'Hats'),
        # ('5', 'Stickers'),
        ('6', 'Home'),
        ('7', 'Luggage'),
    )

    #team = models.ForeignKey('accounts.Team', on_delete=models.CASCADE, default = 0)
    template = models.CharField(default="0", choices=TEMPLATE_CHOICES, max_length=1)
    # template_new = models.ForeignKey(ProductType, on_delete=models.CASCADE, default=1)
    team = models.ForeignKey('accounts.Team', on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=255, blank=True)
    title_de = models.CharField(max_length=255, blank=True)
    title_fr = models.CharField(max_length=255, blank=True)
    title_es = models.CharField(max_length=255, blank=True)
    title_it = models.CharField(max_length=255, blank=True)

    description = models.TextField(blank=True)
    description_de = models.TextField(blank=True)
    description_fr = models.TextField(blank=True)
    description_es = models.TextField(blank=True)
    description_it = models.TextField(blank=True)
    meta_description = models.CharField(max_length=255, blank=True)
    type_uk = models.CharField(max_length=255, blank=True)
    type_fr = models.CharField(max_length=255, blank=True)
    type_de = models.CharField(max_length=255, blank=True)
    type_com = models.CharField(max_length=255, blank=True)
    type_ca = models.CharField(max_length=255, blank=True)
    type_es = models.CharField(max_length=255, blank=True)
    type_it = models.CharField(max_length=255, blank=True)

    type_short = models.CharField(max_length=255, blank=True)
    browse_node_uk = models.CharField(max_length=255, blank=True)
    browse_node_de = models.CharField(max_length=255, blank=True)
    browse_node_fr = models.CharField(max_length=255, blank=True)
    browse_node_ca = models.CharField(max_length=255, blank=True)
    browse_node_jp = models.CharField(max_length=255, blank=True)
    browse_node_es = models.CharField(max_length=255, blank=True)
    browse_node_it = models.CharField(max_length=255, blank=True)

    departments_name = models.CharField(max_length=255, blank=True)
    departments_name_de = models.CharField(max_length=255, blank=True)
    departments_name_fr = models.CharField(max_length=255, blank=True)
    departments_name_es = models.CharField(max_length=255, blank=True)
    departments_name_it = models.CharField(max_length=255, blank=True)

    static_search_tags_1 = models.CharField(max_length=200, blank=True)
    static_search_tag_de = models.CharField(max_length=200, blank=True)
    static_search_tag_fr = models.CharField(max_length=200, blank=True)
    static_search_tag_es = models.CharField(max_length=200, blank=True)
    static_search_tag_it = models.CharField(max_length=200, blank=True)

    bullet_point_1 = models.CharField(max_length=1000, blank=True)
    bullet_point_2 = models.CharField(max_length=1000, blank=True)
    bullet_point_3 = models.CharField(max_length=1000, blank=True)
    bullet_point_4 = models.CharField(max_length=1000, blank=True)
    bullet_point_5 = models.CharField(max_length=1000, blank=True)

    bullet_point_1_de = models.CharField(max_length=1000, blank=True)
    bullet_point_2_de = models.CharField(max_length=1000, blank=True)
    bullet_point_3_de = models.CharField(max_length=1000, blank=True)
    bullet_point_4_de = models.CharField(max_length=1000, blank=True)
    bullet_point_5_de = models.CharField(max_length=1000, blank=True)

    bullet_point_1_fr = models.CharField(max_length=1000, blank=True)
    bullet_point_2_fr = models.CharField(max_length=1000, blank=True)
    bullet_point_3_fr = models.CharField(max_length=1000, blank=True)
    bullet_point_4_fr = models.CharField(max_length=1000, blank=True)
    bullet_point_5_fr = models.CharField(max_length=1000, blank=True)

    bullet_point_1_es = models.CharField(max_length=1000, blank=True)
    bullet_point_2_es = models.CharField(max_length=1000, blank=True)
    bullet_point_3_es = models.CharField(max_length=1000, blank=True)
    bullet_point_4_es = models.CharField(max_length=1000, blank=True)
    bullet_point_5_es = models.CharField(max_length=1000, blank=True)

    bullet_point_1_it = models.CharField(max_length=1000, blank=True)
    bullet_point_2_it = models.CharField(max_length=1000, blank=True)
    bullet_point_3_it = models.CharField(max_length=1000, blank=True)
    bullet_point_4_it = models.CharField(max_length=1000, blank=True)
    bullet_point_5_it = models.CharField(max_length=1000, blank=True)

    material_composition = models.CharField(max_length=255, blank=True)
    material_composition_de = models.CharField(max_length=255, blank=True)
    material_composition_fr = models.CharField(max_length=255, blank=True)
    material_composition_es = models.CharField(max_length=255, blank=True)
    material_composition_it = models.CharField(max_length=255, blank=True)

    fabric_type_uk = models.CharField(max_length=255, blank=True)
    fabric_type_de = models.CharField(max_length=255, blank=True)
    fabric_type_fr = models.CharField(max_length=255, blank=True)
    fabric_type_es = models.CharField(max_length=255, blank=True)
    fabric_type_it = models.CharField(max_length=255, blank=True)

    sleeve_type = models.CharField(max_length=255, blank=True)
    sleeve_type_de = models.CharField(max_length=255, blank=True)
    sleeve_type_fr = models.CharField(max_length=255, blank=True)
    sleeve_type_es = models.CharField(max_length=255, blank=True)
    sleeve_type_it = models.CharField(max_length=255, blank=True)

products/forms.py
from django import forms
from accounts.models import Account


class DesignDownloadForm(forms.Form):
    sku = forms.CharField(max_length=10, widget=forms.TextInput(attrs={"class": "form-control"}))


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50, widget=forms.TextInput(attrs={"class": "form-control"}), required=False)
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True, "class": "form-control"}))
    search_query = forms.CharField(max_length=50, widget=forms.TextInput(attrs={"class": "form-control"}), required=False)
    accounts1 = forms.ModelChoiceField(queryset=Account.objects.all(), widget=forms.Select(attrs={"class": "form-control"}))
    search_tags = forms.CharField(max_length=50, widget=forms.Textarea(attrs={"class": "form-control", "rows": "3"}), required=False)


class MassUploadForm(forms.Form):
    account = forms.ModelChoiceField(queryset=Account.objects.all(), widget=forms.Select(attrs={"class": "form-control"}))
    file = forms.FileField()


class MassDownloadForm(forms.Form):
    skus = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))

products/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Export</title>
    {% load static %}
    <meta charset="utf-8">
    <meta content="utf-8" http-equiv="encoding">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3-legend/1.7.0/d3-legend.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.min.css' %}">
    <script src="{% static 'js/jquery.datetimepicker.full.min.js' %}"></script>
    

<!--<link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />    -->
</head>

<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#MainNav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="MainNav">
                <ul class="nav navbar-nav">
                    {% block categories %}
                    <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'mass_download' %}">Mass Download</a></li>
                        <li><a href="{% url 'generate' %}">Generate</a></li>
                    <li><a href="{% url 'generated_files' %}">Generated Files</a></li>
                    <li><a href="/admin">Admin</a></li>
                    <li><a href="{% url 'designs' %}">Designs</a></li>
                    <li><a href="{% url 'upload' %}">Upload</a></li>
{#                    <li><a href="{% url 'mass_upload' %}">Mass Upload</a></li>#}
                    {% endblock %}
                    {% if user.is_authenticated %}
                    <li>
                    <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}
    
</body>
</html>

<script type="text/javascript">
  $( document ).ready(function() {
    $('#design_settings').click(function() {
        if($('#design_settings_options').is(":visible")) {
            $('#design_settings_options').hide()
            // $('#search_design').hide()
        }
        else 
        {
            $('#design_settings_options').show()
            // $('#search_design').show()
        }
    })

    $('#check_all').click(function() {
        if($(this).is(":checked")) {
            $('.design_checkbox').prop('checked', true);
        }
        else {
            $('.design_checkbox').prop('checked', false);
        }
        
    })
  });
</script>

products/templates/designs.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <form class="form-inline" role="form">
    <div class="row text-center">  
      <a href="#" class="btn btn-primary filter-col" id="design_settings">
        Settings
      </a>
    </div>
    <div class="row text-center" style="display: none; margin-top: 10px;" id="design_settings_options">
      Designs per page
      <input type="text" class="form-control" style="width: 100px;" name="designs_per_page" value="{{pagination_number}}">
      <button type="submit" class="btn btn-success filter-col">
        Set number
      </button>
    </div>
  </form>

  <form class="form-inline" role="form">
    <div class="row text-center" style="margin-top: 10px;">
      <select name="account">
        <option {% if not "account" in request.GET %}disabled selected{% endif %}>All accounts</option>
        {% for account in team_accounts %}
          <option value="{{ account.id }}" {% ifequal request.GET.account account.id|stringformat:'i' %}selected{% endifequal %}>{{ account.name }} ({{account.designs_count}})</option>
        {% endfor %}
      </select>
      <button type="submit" class="btn btn-success filter-col" name="select_account">
        <span class="glyphicon glyphicon-search"></span> Select
      </button>
    </div>
    <div class="row" style="margin-top: 10px;">
      <input type="text" class="form-control" style="width: 300px;" name="search_title" placeholder="Title" value="{{search_title}}">
      <button type="submit" class="btn btn-success" name="search_design">
        <span class="glyphicon glyphicon-search"></span> Search
      </button>
    </div>
  </form>

  <form method="post" action="{% url 'assign_account' %}">{% csrf_token %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th><input type="checkbox" id="check_all"></th>
          <th>#</th>
          <th>Title</th>
          <th>Seach tags</th>
          <th>Sku</th>
          <th>Account</th>
          <th>Design</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for design in designs %}
        {% if design.docfile %}
        <tr>
          <td><input class="design_checkbox" type="checkbox" name="designs_checkboxes" value={{design.id}}></td>
          <th scope="row">{{design.id}}</th>
          <td>{{design.title}}</td>
          <td>{{design.get_search_tags}}</td>
          <td>{{design.sku_code}}</td>
          <td>{{design.account.name}}</td>
          <td>
            {% if design.docfile %}
              {% if '.tif' in design.docfile.url %}
                <img src = "{{design.get_thumbnail}}" style="max-height: 100px; max-width: 100px;" />
              {% else %}
                <img src = "{{design.docfile.url}}" style="max-height: 100px; max-width: 100px;" />
              {% endif %}
            {% endif %}
          </td>
          <td><a class="btn btn-sm btn-warning" target="_blank" href="/designs/edit/{{design.id}}/">Edit</a></td>
        </tr>
        {%endif%}
        {% endfor %}
      </tbody>
    </table>
    <button type="submit" class="btn btn-success filter-col" name="move_designs">
      Move designs
    </button>
    <button type="submit" class="btn btn-success filter-col" name="copy_designs">
      Copy designs
    </button>
    <select name="to_account">
      {% for account in team_accounts %}
        {% ifnotequal request.GET.account account.id|stringformat:'i' %}
          <option value="{{ account.id }}">{{ account.name }}</option>
        {% endifnotequal %}
      {% endfor %}
    </select>

  </form>
  {% if show_pages %}
    <div class="row" style="text-align: center;">
      <div class="pagination">
        <span class="step-links">
            {% if designs.has_previous %}
                <a href="?page={{ designs.previous_page_number }}{{account_text}}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ designs.number }} of {{ designs.paginator.num_pages }}.
            </span>

            {% if designs.has_next %}
                <a href="?page={{ designs.next_page_number }}{{account_text}}">next</a>
            {% endif %}
        </span>
      </div>
      <div>
        <a class="btn btn-lg btn-success" href="?page=show_all{{account_text}}">Show All</a>
      </div>
    </div>
  {% endif %}
</div>
{% endblock %}

products/templates/edit_design.html
{% extends 'base.html' %}

{% block body %}

    <form action="/designs/update/{{ design.id }}/" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                {% if design.docfile %}
                    {% if '.tif' in design.docfile.url %}
                        <img src="{{ design.get_thumbnail }}" style="max-height: 100px; max-width: 100px;"/>
                    {% else %}
                        <img src="{{ design.docfile.url }}" style="max-height: 100px; max-width: 100px;"/>
                    {% endif %}
                {% endif %}
            </div>

            <div class="row">
                <div class="form-group col-xs-4">
                    <label>Title</label>
                    <input class="form-control" id="id_title" name="title" type="text" value="{{ design.title }}"/>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-xs-4">
                    <label>Search tags</label>
{#                    {{ form.search_tags }}#}
                    <textarea class="form-control" id="id_search_tags" name="search_tags" type="text">{{ design.search_tags }}</textarea>
                </div>
            </div>

            <div class="row">
                <input type="submit">
            </div>
        </div>
    </form>
{% endblock %}

products/templates/generate.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <form action = "{% url 'generate' %}" method="post">
  {% csrf_token %}
    <div class="row">
      <div class="form-group col-lg-2">          
        <div class="input-group date" id="id_date_from_picker">
          <input class="form-control" id="id_date_from" name="date_from" type="text"/>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>  
      </div>
    </div>

    <script>
      jQuery('#id_date_from').datetimepicker({
        format:'Y-m-d H:i',
      });
    </script>
    <div class="row">
      <div class="form-group col-lg-6">
        <select class="form-control" name="accounts1" id="id_myselect">
          {% for account in accounts %}
              <option value="{{ account.id }}">{{ account.name }}</option>
          {% endfor %}
        </select>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-lg-6">
        <input class="form-control" id="id_comment" maxlength="250" name="comment" placeholdeR="Comment.." type="text" />
      </div>
    </div>

    <div class="row">
      <div class="form-group col-lg-2">
        <input id="id_black_only" name="black_only" type="checkbox" /> Black only
      </div>
    </div>

    {% for product in products %}
        <h3>{{ product.title }}</h3>
        <p><i>{{ product.meta_description }}</i></p>
        {% for color_variation in product.color_variations %}
            <div class="checkbox">
                <label for="id_variations_{{color_variation.id}}"><input id="id_variations_{{color_variation.id}}" name="variations" type="checkbox" value="{{color_variation.id}}" /> {{color_variation.color_name}} </label>
            </div>
        {% endfor %}
    {% endfor %}

    <input type="submit" class="btn btn-success" name="generate1" value="Generate!">
    <input type="submit" class="btn btn-success" name="generate2" value="Generate Test!">
        
  </form>
</div>

{% endblock %}

products/templates/generated_files.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        {% if messages %}
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-success">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
        {% for generation in generations %}
            <div class="row">
                <b>{{ generation.created_at }} ({{ generation.completed_rows }}/{{ generation.total_rows }} designs completed. Failed: <span {% if generation.failed_rows > 0 %}style="color: red"{% endif %}>{{ generation.failed_rows }}</span>)</b>{% if generation.failed_designs|length > 0 %} <a href="{% url 'failed_designs' generation_id=generation.id %}">Failed desings</a>{% endif %}
                <a href="{% url 'delete_batch' batch_id=generation.id %}">delete</a>
                {% if not generation.generated %}
                    <div style="color: red;">GENERATING</div>
                {% endif %}
            </div>
            {% if generation.uk_files %}
                <div class="row">
                    UK FILES
                </div>
                {% for file in generation.uk_files %}
                    <div class="row">
                        <!-- <a href="{{file.file_path}}" download>{{file.file_name}}</a> -->
                        <a href="{{ file.file_path }}" download>{{ file.file_name }}</a>
                    </div>
                {% endfor %}
            {% endif %}


            {% if generation.de_files %}
                <div class="row">
                    DE FILES
                </div>
                {% for file in generation.de_files %}
                    <div class="row">
                        <!-- <a href="{{file.file_path}}" download>{{file.file_name}}</a> -->
                        <a href="{{ file.file_path }}" download>{{ file.file_name }}</a>
                    </div>
                {% endfor %}
            {% endif %}

            {% if generation.fr_files %}
                <div class="row">
                    FR FILES
                </div>
                {% for file in generation.fr_files %}
                    <div class="row">
                        <!-- <a href="{{file.file_path}}" download>{{file.file_name}}</a> -->
                        <a href="{{ file.file_path }}" download>{{ file.file_name }}</a>
                    </div>
                {% endfor %}
            {% endif %}

            {% if generation.es_files %}
                <div class="row">
                    ES FILES
                </div>
                {% for file in generation.es_files %}
                    <div class="row">
                        <!-- <a href="{{file.file_path}}" download>{{file.file_name}}</a> -->
                        <a href="{{ file.file_path }}" download>{{ file.file_name }}</a>
                    </div>
                {% endfor %}
            {% endif %}

            {% if generation.it_files %}
                <div class="row">
                    IT FILES
                </div>
                {% for file in generation.it_files %}
                    <div class="row">
                        <!-- <a href="{{file.file_path}}" download>{{file.file_name}}</a> -->
                        <a href="{{ file.file_path }}" download>{{ file.file_name }}</a>
                    </div>
                {% endfor %}
            {% endif %}

            {% if generation.noname_files %}
                <div class="row">
                    UNKNOWN FILES
                </div>
                {% for file in generation.noname_files %}
                    <div class="row">
                        <!-- <a href="{{file.file_path}}" download>{{file.file_name}}</a> -->
                        <a href="{{ file.file_path }}" download>{{ file.file_name }}</a>
                    </div>
                {% endfor %}
            {% endif %}
            <br/>
        {% endfor %}
    </div>
{% endblock %}

products/templates/generation_errors.html
{% extends 'base.html' %}

{% block body %}
  {% for error in errors %}
  <div class="row">
    <div class="col-sm-6">
      {{error.design.title}}
    </div>
    <div class="col-sm-2">
      {{error.design.sku_code}}
    </div>
    <div class="col-sm-2">
      <!-- <img src = "/media/designs/{{design.filename}}" style="max-height: 100px;" /> -->
      <img src = "{{error.design.docfile.url}}" style="max-height: 100px;" />
    </div>
  </div>
  {% endfor %}

{% endblock %}

products/templates/mass_download.html
{% extends 'base.html' %}

{% block body %}

    <form action="" method="POST">
    {% csrf_token %}
    <div class="container">
            <div class="row">
                <div class="form-group col-xs-4">
                    <label>SKUs</label>
                    {{ form.skus }}
                </div>
            </div>

            <div class="row">
                <div class="form-group col-xs-4">
                    <input class="btn btn-success" type="submit">
                </div>
            </div>
        </div>
    </form>
{% endblock %}